INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AF', 'Afghanistan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AL', 'Albania', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DZ', 'Algeria', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AS', 'American Samoa', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AD', 'Andorra', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AO', 'Angola', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AI', 'Anguilla', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AQ', 'Antarctica', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AG', 'Antigua and Barbuda', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AR', 'Argentina', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AM', 'Armenia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AW', 'Aruba', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AU', 'Australia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AT', 'Austria', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AZ', 'Azerbaijan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BS', 'Bahamas', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BH', 'Bahrain', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BD', 'Bangladesh', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BB', 'Barbados', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BY', 'Belarus', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BE', 'Belgium', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BZ', 'Belize', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BJ', 'Benin', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BM', 'Bermuda', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BT', 'Bhutan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BO', 'Bolivia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BA', 'Bosnia and Herzegovina', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BW', 'Botswana', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BV', 'Bouvet Island', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BR', 'Brazil', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IO', 'British Indian Ocean Territory', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VG', 'British Virgin Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BN', 'Brunei', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BG', 'Bulgaria', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BF', 'Burkina Faso', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BI', 'Burundi', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KH', 'Cambodia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CM', 'Cameroon', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CA', 'Canada', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CV', 'Cape Verde', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KY', 'Cayman Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CF', 'Central African Republic', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TD', 'Chad', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CL', 'Chile', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CN', 'China', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CX', 'Christmas Island', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CC', 'Cocos [Keeling] Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CO', 'Colombia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KM', 'Comoros', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CG', 'Congo - Brazzaville', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CD', 'Congo - Kinshasa', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CK', 'Cook Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CR', 'Costa Rica', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HR', 'Croatia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CU', 'Cuba', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CY', 'Cyprus', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CZ', 'Czech Republic', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CI', 'Côte d’Ivoire', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DK', 'Denmark', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DJ', 'Djibouti', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DM', 'Dominica', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DO', 'Dominican Republic', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('EC', 'Ecuador', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('EG', 'Egypt', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SV', 'El Salvador', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GQ', 'Equatorial Guinea', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ER', 'Eritrea', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('EE', 'Estonia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ET', 'Ethiopia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FK', 'Falkland Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FO', 'Faroe Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FJ', 'Fiji', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FI', 'Finland', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FR', 'France', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GF', 'French Guiana', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PF', 'French Polynesia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TF', 'French Southern Territories', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GA', 'Gabon', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GM', 'Gambia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GE', 'Georgia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DE', 'Germany', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GH', 'Ghana', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GI', 'Gibraltar', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GR', 'Greece', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GL', 'Greenland', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GD', 'Grenada', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GP', 'Guadeloupe', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GU', 'Guam', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GT', 'Guatemala', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GG', 'Guernsey', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GN', 'Guinea', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GW', 'Guinea-Bissau', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GY', 'Guyana', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HT', 'Haiti', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HM', 'Heard Island and McDonald Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HN', 'Honduras', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HK', 'Hong Kong', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HU', 'Hungary', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IS', 'Iceland', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IN', 'India', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ID', 'Indonesia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IR', 'Iran', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IQ', 'Iraq', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IE', 'Ireland', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IM', 'Isle of Man', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IL', 'Israel', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IT', 'Italy', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('JM', 'Jamaica', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('JP', 'Japan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('JE', 'Jersey', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('JO', 'Jordan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KZ', 'Kazakhstan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KE', 'Kenya', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KI', 'Kiribati', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KW', 'Kuwait', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KG', 'Kyrgyzstan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LA', 'Laos', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LV', 'Latvia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LB', 'Lebanon', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LS', 'Lesotho', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LR', 'Liberia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LY', 'Libya', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LI', 'Liechtenstein', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LT', 'Lithuania', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LU', 'Luxembourg', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MO', 'Macau SAR China', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MK', 'Macedonia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MG', 'Madagascar', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MW', 'Malawi', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MY', 'Malaysia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MV', 'Maldives', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ML', 'Mali', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MT', 'Malta', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MH', 'Marshall Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MQ', 'Martinique', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MR', 'Mauritania', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MU', 'Mauritius', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('YT', 'Mayotte', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MX', 'Mexico', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FM', 'Micronesia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MD', 'Moldova', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MC', 'Monaco', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MN', 'Mongolia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ME', 'Montenegro', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MS', 'Montserrat', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MA', 'Morocco', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MZ', 'Mozambique', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MM', 'Myanmar [Burma]', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NA', 'Namibia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NR', 'Nauru', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NP', 'Nepal', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NL', 'Netherlands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AN', 'Netherlands Antilles', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NC', 'New Caledonia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NZ', 'New Zealand', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NI', 'Nicaragua', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NE', 'Niger', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NG', 'Nigeria', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NU', 'Niue', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NF', 'Norfolk Island', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KP', 'North Korea', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MP', 'Northern Mariana Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NO', 'Norway', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('OM', 'Oman', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PK', 'Pakistan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PW', 'Palau', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PS', 'Palestinian Territories', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PA', 'Panama', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PG', 'Papua New Guinea', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PY', 'Paraguay', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PE', 'Peru', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PH', 'Philippines', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PN', 'Pitcairn Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PL', 'Poland', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PT', 'Portugal', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PR', 'Puerto Rico', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('QA', 'Qatar', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('RO', 'Romania', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('RU', 'Russia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('RW', 'Rwanda', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('RE', 'Réunion', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BL', 'Saint Barthélemy', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SH', 'Saint Helena', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KN', 'Saint Kitts and Nevis', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LC', 'Saint Lucia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MF', 'Saint Martin', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PM', 'Saint Pierre and Miquelon', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VC', 'Saint Vincent and the Grenadines', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('WS', 'Samoa', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SM', 'San Marino', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SA', 'Saudi Arabia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SN', 'Senegal', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('RS', 'Serbia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CS', 'Serbia and Montenegro', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SC', 'Seychelles', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SL', 'Sierra Leone', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SG', 'Singapore', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SK', 'Slovakia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SI', 'Slovenia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SB', 'Solomon Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SO', 'Somalia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ZA', 'South Africa', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GS', 'South Georgia and the South Sandwich Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KR', 'South Korea', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ES', 'Spain', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LK', 'Sri Lanka', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SD', 'Sudan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SR', 'Suriname", "locale', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SJ', 'Svalbard and Jan Mayen', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SZ', 'Swaziland', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SE', 'Sweden', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CH', 'Switzerland', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SY', 'Syria', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ST', 'São Tomé and Príncipe', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TW', 'Taiwan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TJ', 'Tajikistan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TZ', 'Tanzania', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TH', 'Thailand', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TL', 'Timor-Leste', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TG', 'Togo', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TK', 'Tokelau', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TO', 'Tonga', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TT', 'Trincodead and Tobago', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TN', 'Tunisia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TR', 'Turkey', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TM', 'Turkmenistan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TC', 'Turks and Caicos Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TV', 'Tuvalu', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('UM', 'U.S. Minor Outlying Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VI', 'U.S. Virgin Islands', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('UG', 'Uganda', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('UA', 'Ukraine', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AE', 'United Arab Emirates', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GB', 'United Kingdom', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('US', 'United States', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ZZ', 'Unknown or Invalcode Region', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('UY', 'Uruguay', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('UZ', 'Uzbekistan', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VU', 'Vanuatu', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VA', 'Vatican City', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VE', 'Venezuela', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VN', 'Vietnam', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('WF', 'Wallis and Futuna', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('EH', 'Western Sahara', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('YE', 'Yemen', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ZM', 'Zambia', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ZW', 'Zimbabwe', 'EN');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AX', 'Åland Islands', 'EN');

-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BQ', 'British Antarctic Territory', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CT', 'Canton and Enderbury Islands', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DD', 'East Germany', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FQ', 'French Southern and Antarctic Territories', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FX', 'Metropolitan France', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('JT', 'Johnston Island', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MI', 'Mcodeway Islands', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NQ', 'Dronning Maud Land', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NT', 'Neutral Zone', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PC', 'Pacific Islands Trust Territory', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PU', 'U.S. Miscellaneous Pacific Islands', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PZ', 'Panama Canal Zone', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SU', 'Union of Soviet Socialist Republics', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VD', 'North Vietnam', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('WK', 'Wake Island', 'EN');
-- INSERT INTO "country_names" ("code", "name", "locale") VALUES ('YD', 'People''s Democratic Republic of Yemen', 'EN');