INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AU', 'Австралия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AT', 'Австрия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AZ', 'Азербайджан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AX', 'Аландские острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AL', 'Албания', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DZ', 'Алжир', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VI', 'Американские Виргинские острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AS', 'Американское Самоа', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AO', 'Ангола', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AI', 'Ангуилла', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AD', 'Андорра', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AQ', 'Антарктика', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AG', 'Антигуа и Барбуда', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AR', 'Аргентина', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AM', 'Армения', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AW', 'Аруба', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AF', 'Афганистан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BS', 'Багамские острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BD', 'Бангладеш', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BB', 'Барбадос', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BH', 'Бахрейн', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BY', 'Беларусь', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BZ', 'Белиз', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BE', 'Бельгия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BJ', 'Бенин', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BM', 'Бермудские Острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BG', 'Болгария', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BO', 'Боливия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BA', 'Босния и Герцеговина', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BW', 'Ботсвана', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BR', 'Бразилия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IO', 'Британская территория в Индийском океане', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VG', 'Британские Виргинские Острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BN', 'Бруней Даруссалам', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BF', 'Буркина Фасо', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BI', 'Бурунди', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BT', 'Бутан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VU', 'Вануату', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VA', 'Ватикан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GB', 'Великобритания', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HU', 'Венгрия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VE', 'Венесуэла', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('UM', 'Внешние малые острова (США)', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TL', 'Восточный Тимор', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VN', 'Вьетнам', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GA', 'Габон', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HT', 'Гаити', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GY', 'Гайана', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GM', 'Гамбия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GH', 'Гана', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GP', 'Гваделупа', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GT', 'Гватемала', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GN', 'Гвинея', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GW', 'Гвинея-Биссау', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DE', 'Германия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GG', 'Гернси', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GI', 'Гибралтар', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HN', 'Гондурас', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HK', 'Гонконг', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GD', 'Гренада', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GL', 'Гренландия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GR', 'Греция', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GE', 'Грузия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GU', 'Гуам', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DK', 'Дания', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CD', 'Демократическая Республика Конго', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('JE', 'Джерси', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DJ', 'Джибути', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DO', 'Доминиканская Республика', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('EG', 'Египет', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ZM', 'Замбия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('EH', 'Западная Сахара', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ZW', 'Зимбабве', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IL', 'Израиль', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IN', 'Индия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ID', 'Индонезия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('JO', 'Иордания', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IQ', 'Ирак', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IR', 'Иран', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IE', 'Ирландия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IS', 'Исландия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ES', 'Испания', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IT', 'Италия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('YE', 'Йемен', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KZ', 'Казахстан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KY', 'Каймановы острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KH', 'Камбоджа', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CM', 'Камерун', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CA', 'Канада', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('QA', 'Катар', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KE', 'Кения', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CY', 'Кипр', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KI', 'Кирибати', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CN', 'Китай', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CC', 'Кокосовые острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CO', 'Колумбия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KM', 'Коморские Острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CG', 'Конго', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KP', 'Корейская Народно-Демократическая Республика', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CR', 'Коста-Рика', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CI', 'Кот д’Ивуар', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CU', 'Куба', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KW', 'Кувейт', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KG', 'Кыргызстан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LA', 'Лаос', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LV', 'Латвия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LS', 'Лесото', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LR', 'Либерия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LB', 'Ливан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LY', 'Ливия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LT', 'Литва', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LI', 'Лихтенштейн', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LU', 'Люксембург', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MU', 'Маврикий', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MR', 'Мавритания', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MG', 'Мадагаскар', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('YT', 'Майотта', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MO', 'Макао (особый административный район КНР)', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MK', 'Македония', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MW', 'Малави', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MY', 'Малайзия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ML', 'Мали', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MV', 'Мальдивы', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MT', 'Мальта', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MA', 'Марокко', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MQ', 'Мартиник', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MH', 'Маршалловы Острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MX', 'Мексика', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MZ', 'Мозамбик', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MD', 'Молдова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MC', 'Монако', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MN', 'Монголия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MS', 'Монсеррат', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MM', 'Мьянма', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NA', 'Намибия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NR', 'Науру', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ZZ', 'Неизвестный или недействительный регион', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NP', 'Непал', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NE', 'Нигер', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NG', 'Нигерия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AN', 'Нидерландские Антильские острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NL', 'Нидерланды', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NI', 'Никарагуа', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NU', 'Ниуе', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NZ', 'Новая Зеландия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NC', 'Новая Каледония', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NO', 'Норвегия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('AE', 'Объединенные Арабские Эмираты', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('OM', 'Оман', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BV', 'Остров Буве', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('DM', 'Остров Доминика', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('IM', 'Остров Мэн', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('NF', 'Остров Норфолк', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CX', 'Остров Рождества', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('BL', 'Остров Святого Бартоломея', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MF', 'Остров Святого Мартина', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SH', 'Остров Святой Елены', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CV', 'Острова Зеленого Мыса', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CK', 'Острова Кука', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TC', 'Острова Тёркс и Кайкос', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HM', 'Острова Херд и Макдональд', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PK', 'Пакистан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PW', 'Палау', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PS', 'Палестинская автономия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PA', 'Панама', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PG', 'Папуа-Новая Гвинея', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PY', 'Парагвай', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PE', 'Перу', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PN', 'Питкерн', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PL', 'Польша', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PT', 'Португалия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PR', 'Пуэрто-Рико', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KR', 'Республика Корея', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('RE', 'Реюньон', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('RU', 'Россия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('RW', 'Руанда', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('RO', 'Румыния', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('US', 'США', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SV', 'Сальвадор', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('WS', 'Самоа', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SM', 'Сан-Марино', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ST', 'Сан-Томе и Принсипи', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SA', 'Саудовская Аравия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SZ', 'Свазиленд', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SJ', 'Свальбард и Ян-Майен', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('MP', 'Северные Марианские Острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SC', 'Сейшельские Острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PM', 'Сен-Пьер и Микелон', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SN', 'Сенегал', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('VC', 'Сент-Винсент и Гренадины', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('KN', 'Сент-Киттс и Невис', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LC', 'Сент-Люсия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('RS', 'Сербия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CS', 'Сербия и Черногория', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SG', 'Сингапур', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SY', 'Сирийская Арабская Республика', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SK', 'Словакия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SI', 'Словения', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SB', 'Соломоновы Острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SO', 'Сомали', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SD', 'Судан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SR', 'Суринам', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SL', 'Сьерра-Леоне', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TJ', 'Таджикистан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TH', 'Таиланд', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TW', 'Тайвань', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TZ', 'Танзания', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TG', 'Того', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TK', 'Токелау', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TO', 'Тонга', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TT', 'Тринидад и Тобаго', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TV', 'Тувалу', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TN', 'Тунис', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TM', 'Туркменистан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TR', 'Турция', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('UG', 'Уганда', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('UZ', 'Узбекистан', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('UA', 'Украина', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('WF', 'Уоллис и Футуна', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('UY', 'Уругвай', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FO', 'Фарерские острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FM', 'Федеративные Штаты Микронезии', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FJ', 'Фиджи', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PH', 'Филиппины', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FI', 'Финляндия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FK', 'Фолклендские острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('FR', 'Франция', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GF', 'Французская Гвиана', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('PF', 'Французская Полинезия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TF', 'Французские Южные Территории', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('HR', 'Хорватия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CF', 'Центрально-Африканская Республика', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('TD', 'Чад', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ME', 'Черногория', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CZ', 'Чешская республика', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CL', 'Чили', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('CH', 'Швейцария', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('SE', 'Швеция', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('LK', 'Шри-Ланка', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('EC', 'Эквадор', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GQ', 'Экваториальная Гвинея', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ER', 'Эритрея', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('EE', 'Эстония', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ET', 'Эфиопия', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('ZA', 'Южная Африка', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('GS', 'Южная Джорджия и Южные Сандвичевы Острова', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('JM', 'Ямайка', 'RU');
INSERT INTO "country_names" ("code", "name", "locale") VALUES ('JP', 'Япония', 'RU');